---
title: DEPT
timezone: GMT
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
email: naamanh10@gmail.com
description: Deal or No Deal
baseurl: ''
url: http://mscc.naamanhudson.com/
markdown: kramdown
